name: Manatí Base Config
description: "Provides the base config for contrib modules used by Manati."
type: module
package: Manatí
core_version_requirement: ^8.8 || ^9
dependencies:
  - admin_toolbar:admin_toolbar_tools
  - better_exposed_filters:better_exposed_filters
  - config_split:config_split
  - devel:devel
  - environment_indicator:environment_indicator
  - focal_point:focal_point
  - image_style_quality:image_style_quality
  - media_entity_facebook:media_entity_facebook
  - media_entity_instagram:media_entity_instagram
  - media_entity_twitter:media_entity_twitter
  - media_library:media_library
  - metatag:metatag_open_graph
  - metatag:metatag_twitter_cards
  - pathauto:pathauto
  - quicklink:quicklink
  - retina_images:retina_images
  - seckit:seckit
  - shs:shs
  - stage_file_proxy:stage_file_proxy
  - svg_image:svg_image
  - twig_tweak:twig_tweak
  - xmlsitemap:xmlsitemap_engines
